### ISSUE TITLE
I get an error whenever I try to download anything

### ISSUE THREAD

**Issue by Milloper** [Kycklingar/pbooru-downloader#1]
I get an error whenever I try to download anything and adding text to the path gives me the error: "download.py: error: unrecognized arguments: added text"

PS F:\pbooru-downloader-master> python download.py --proxy socks5h://localhost:9150 --tor-browser --filenamer filename_compiler.py -a "striped" path
Traceback (most recent call last):
  File "F:\pbooru-downloader-master\download.py", line 356, in <module>
    main()
  File "F:\pbooru-downloader-master\download.py", line 28, in main
    compiler = FCompilers(args.filenamer)
  File "F:\pbooru-downloader-master\download.py", line 202, in __init__
    self.add(line)
  File "F:\pbooru-downloader-master\download.py", line 207, in add
    self.compilers.append(FilenameCompiler(string))
  File "F:\pbooru-downloader-master\filename_compiler.py", line 13, in __init__
    lex(string, self.tokenStream)
  File "F:\pbooru-downloader-master\filedef.py", line 6, in lex
    return l.lex()
  File "F:\pbooru-downloader-master\filedef.py", line 52, in lex
    state = state()
  File "F:\pbooru-downloader-master\filedef.py", line 215, in lexNamespace
    raise SyntaxError("Sequence end in namespace state:\n %s" % self.text[:start])
filedef.SyntaxError: Sequence end in namespace state:
 return "<%s:%s:
filedef.SyntaxError: Sequence end in namespace state:
 return "<%s:%s:

**Comment by Kycklingar** [comment]
Sorry for the delay.

The issue is you are trying to provide the filename_compiler script as a filename definition file. 
Drop `--filenamer filename_compiler.py` or use the supplied (or create your own) file `--filenamer filenames.txt`

`--proxy socks5h://localhost:9150` and `--tor-browser` Is redundant as they both mean the same thing. Use just `--tor-browser`.

Note by default it is assumed you will use a local IPFS gateway. If you would rather use the sites gateway add `--gateway-proxy socks5h://localhost:9150 --gateway http://xbzszf4a4z46wjac7pgbheizjgvwaf3aydtjxg7vsn3onhlot6sppfad.onion`

So the final command may look like `python download.py --tor-browser --gateway-proxy socks5h://localhost:9150 --gateway http://xbzszf4a4z46wjac7pgbheizjgvwaf3aydtjxg7vsn3onhlot6sppfad.onion -a "striped" path`

**Comment by Ranze61** [comment]
So, with the line you gave me I got a different error:

Traceback (most recent call last):
  File "F:\pbooru-downloader-master\download.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

and by removing line 2 in "download.py" instead I got 

Traceback (most recent call last):
  File "F:\pbooru-downloader-master\download.py", line 355, in <module>
    main()
  File "F:\pbooru-downloader-master\download.py", line 35, in main
    for post in search:
  File "F:\pbooru-downloader-master\download.py", line 247, in __next__
    self.fetchNextPage()
  File "F:\pbooru-downloader-master\download.py", line 274, in fetchNextPage
    resp = requests.get(self.url + "/api/v1/posts", proxies=self.proxies, params=params)
NameError: name 'requests' is not defined

I tell you in advance that I'm a noob with python

**Comment by Milloper** [comment]
Thank you, I was able to make the downloader work now :)
