### ISSUE TITLE
Got a new error

### ISSUE THREAD

**Issue by Milloper** [Kycklingar/pbooru-downloader#2]
I tried running this line:

python download.py --tor-browser --gateway-proxy socks5h://localhost:9150 --gateway http://xbzszf4a4z46wjac7pgbheizjgvwaf3aydtjxg7vsn3onhlot6sppfad.onion -a "creator:petresko" path

But instead of working it gave me this long error, I already tried other tags such as "stripes" but I got the same result

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\socks.py", line 809, in connect
    negotiate(self, dest_addr, dest_port)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\socks.py", line 443, in _negotiate_SOCKS5
    self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\socks.py", line 533, in _SOCKS5_request
    raise SOCKS5Error("{:#04x}: {}".format(status, error))
socks.SOCKS5Error: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\contrib\socks.py", line 96, in _new_conn
    conn = socks.create_connection(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\socks.py", line 209, in create_connection
    raise err
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\socks.py", line 814, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\contrib\socks.py", line 127, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSConnection object at 0x00000282A119AD10>: Failed to establish a new connection: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPConnectionPool(host='owmvhpxyisu6fgd7r2fcswgavs7jly4znldaey33utadwmgbbp4pysad.onion', port=80): Max retries exceeded with url: /api/v1/posts?tags=creator%3Apetresko&offset=0&order=asc (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x00000282A119AD10>: Failed to establish a new connection: 0x06: TTL expired'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pbooru-downloader-master\download.py", line 356, in <module>
    main()
  File "F:\pbooru-downloader-master\download.py", line 36, in main
    for post in search:
  File "F:\pbooru-downloader-master\download.py", line 248, in __next__
    self.fetchNextPage()
  File "F:\pbooru-downloader-master\download.py", line 275, in fetchNextPage
    resp = requests.get(self.url + "/api/v1/posts", proxies=self.proxies, params=params)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPConnectionPool(host='owmvhpxyisu6fgd7r2fcswgavs7jly4znldaey33utadwmgbbp4pysad.onion', port=80): Max retries exceeded with url: /api/v1/posts?tags=creator%3Apetresko&offset=0&order=asc (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x00000282A119AD10>: Failed to establish a new connection: 0x06: TTL expired'))

**Comment by Milloper** [comment]
The line
python download.py --tor-browser --gateway-proxy socks5h://localhost:9150 --gateway http://xbzszf4a4z46wjac7pgbheizjgvwaf3aydtjxg7vsn3onhlot6sppfad.onion -a "striped" path
Gives me the error:
raceback (most recent call last):
  File "F:\pbooru-downloader-master\download.py", line 356, in <module>
    main()
  File "F:\pbooru-downloader-master\download.py", line 46, in main
    storage.write(cid, filename, gateway.get(cid), getTags(post))
  File "F:\pbooru-downloader-master\download.py", line 304, in get
    resp.raise_for_status()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://xbzszf4a4z46wjac7pgbheizjgvwaf3aydtjxg7vsn3onhlot6sppfad.onion/ipfs/bafybeifs2yubsgykhbp6pcnjdvs4hgoa37m6ynwxpo2sj2n3s52kyz2qly

**Comment by Milloper** [comment]
It seems like the server works again now, I'll close the issue just in case
